<?php
/**
 * PHP-based i18n Extractor & Reconciler
 *
 * This script extracts all gettext keys from src/ recursively,
 * uses the old en_US PO catalog to map French translations back to English msgid/msgstr,
 * and regenerates messages.pot, and PO files for English and Arabic.
 */

// 1. Scan directory recursively for PHP files
function getPhpFiles($dir) {
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
    $files = [];
    foreach ($iterator as $file) {
        if ($file->isFile() && $file->getExtension() === 'php') {
            $files[] = $file->getPathname();
        }
    }
    return $files;
}

// 2. Extract gettext keys from a file
function extractKeysFromFiles($files) {
    $keys = [];
    // Regex matching _('string') and _("string"), handling escaped quotes
    $pattern = '/(?<!\w)_\(\s*(\'((?:[^\'\\\\]|\\\\.)*)\'|"((?:[^"\\\\]|\\\\.)*)")\s*\)/';

    foreach ($files as $file) {
        $content = file_get_contents($file);
        if (preg_match_all($pattern, $content, $matches)) {
            foreach ($matches[1] as $matchedString) {
                // Determine quote type and unescape
                $quote = $matchedString[0];
                $inner = substr($matchedString, 1, -1);
                if ($quote === "'") {
                    $unescaped = stripcslashes($inner);
                } else {
                    $unescaped = stripcslashes($inner);
                }

                if (!empty($unescaped)) {
                    $keys[$unescaped][] = $file;
                }
            }
        }
    }
    return $keys;
}

// 3. Parse old PO file to map French to English
function parseOldPo($filepath) {
    if (!file_exists($filepath)) {
        return [];
    }

    $lines = file($filepath);
    $map = [];
    $current_msgid = '';

    foreach ($lines as $line) {
        $line = trim($line);
        if (strpos($line, 'msgid "') === 0) {
            $current_msgid = substr($line, 7, -1);
        } elseif (strpos($line, 'msgstr "') === 0 && !empty($current_msgid)) {
            $current_msgstr = substr($line, 8, -1);
            if (!empty($current_msgstr)) {
                // Map the French translation (msgstr) to English (msgid)
                $map[$current_msgstr] = $current_msgid;
            }
            $current_msgid = '';
        }
    }
    return $map;
}

// Main Execution
$srcDir = __DIR__ . '/src';
$files = getPhpFiles($srcDir);
$extracted = extractKeysFromFiles($files);
$unique_keys = array_keys($extracted);
sort($unique_keys);

echo "Total PHP files scanned: " . count($files) . "\n";
echo "Total unique gettext keys found: " . count($unique_keys) . "\n";

// Parse old English translation to preserve translations
$oldPoPath = __DIR__ . '/locale/en_US/LC_MESSAGES/messages.po';
$french_to_english = parseOldPo($oldPoPath);
echo "Loaded " . count($french_to_english) . " translations from old en_US PO catalog.\n";

// Generate POT Template
$potContent = "# POT Template Generated by extract_i18n.php\n";
$potContent .= "# Language: French (Pivot)\n\n";

foreach ($unique_keys as $key) {
    $escapedKey = addcslashes($key, "\"\n\r\t\\");
    foreach ($extracted[$key] as $refFile) {
        $relativeRef = str_replace(__DIR__ . '/', '', $refFile);
        $potContent .= "#: " . $relativeRef . "\n";
    }
    $potContent .= "msgid \"" . $escapedKey . "\"\n";
    $potContent .= "msgstr \"\"\n\n";
}

file_put_contents(__DIR__ . '/locale/messages.pot', $potContent);
echo "Generated locale/messages.pot successfully.\n";

// Generate English PO File
$enPoContent = "# English PO Catalog\n";
$enPoContent .= "msgid \"\"\n";
$enPoContent .= "msgstr \"\"\n";
$enPoContent .= "\"Language: en_US\\n\"\n";
$enPoContent .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n\n";

$mapped_count = 0;
foreach ($unique_keys as $key) {
    $escapedKey = addcslashes($key, "\"\n\r\t\\");
    $english_translation = $french_to_english[$key] ?? '';

    if (!empty($english_translation)) {
        $mapped_count++;
    } else {
        // If no mapping, check if key is already English (fallback to key itself)
        if (preg_match('/^[a-zA-Z0-9\s.,;:!?\'"()%-]+$/', $key)) {
            $english_translation = $key;
        }
    }

    $escapedTranslation = addcslashes($english_translation, "\"\n\r\t\\");

    foreach ($extracted[$key] as $refFile) {
        $relativeRef = str_replace(__DIR__ . '/', '', $refFile);
        $enPoContent .= "#: " . $relativeRef . "\n";
    }
    $enPoContent .= "msgid \"" . $escapedKey . "\"\n";
    $enPoContent .= "msgstr \"" . $escapedTranslation . "\"\n\n";
}

file_put_contents(__DIR__ . '/locale/en_US/LC_MESSAGES/messages.po', $enPoContent);
echo "Generated locale/en_US/LC_MESSAGES/messages.po successfully with " . $mapped_count . " preserved English translations.\n";

// Generate Arabic PO File
$arPoContent = "# Arabic PO Catalog\n";
$arPoContent .= "msgid \"\"\n";
$arPoContent .= "msgstr \"\"\n";
$arPoContent .= "\"Language: ar\\n\"\n";
$arPoContent .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n\n";

foreach ($unique_keys as $key) {
    $escapedKey = addcslashes($key, "\"\n\r\t\\");

    foreach ($extracted[$key] as $refFile) {
        $relativeRef = str_replace(__DIR__ . '/', '', $refFile);
        $arPoContent .= "#: " . $relativeRef . "\n";
    }
    $arPoContent .= "msgid \"" . $escapedKey . "\"\n";
    $arPoContent .= "msgstr \"\"\n\n";
}

file_put_contents(__DIR__ . '/locale/ar/LC_MESSAGES/messages.po', $arPoContent);
echo "Generated locale/ar/LC_MESSAGES/messages.po successfully with empty strings ready for Phase 5.\n";
